import { Inter } from "next/font/google";
import SidebarWithHeader from "@/components/Sidebar";
import "./globals.css";
import { ChakraProvider } from '@chakra-ui/react'
import * as React from 'react'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <SidebarWithHeader>{children}</SidebarWithHeader>
        </ChakraProvider>
      </body>
    </html>
  );
}
